### ISSUE TITLE
Add flag to database

### ISSUE THREAD

**Issue by Valdimus** [OpenPathView/batchPanoMaker#4]
Can you add a flag to the data base for a "cp" that show that cp is optimized.

**Comment by naegi** [comment]
Yes; I can.
I suppose it should be an boolean ? 
Is the flag nullable ? For now I allow the flag to be null.

**Comment by Benvii** [comment]
Yes it's a boolean value.
It should not be nullable and it's default value must be "false".

Thanks


Le 27 janvier 2017 21:10:25 GMT+01:00, naegi <notifications@github.com> a écrit :
>Yes; I can.
>I suppose it should be an boolean ? 
>Is the flag nullable ? For now I allow the flag to be null.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenPathView/batchPanoMaker/issues/4#issuecomment-275762256

-- 
Benjamin BERNARD
Porteur du projet Open Path View http://openpathview.fr 
Maison du libre Brest http://mdl29.net

**Comment by naegi** [comment]
Done on commit cbb3e66
